#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 FalconPulsar Contributors
#
# =============================================================================
# sync-icons.sh -- propagate shared/icons/icons.def into both tray apps.
#
# shared/icons/icons.def is the single source of truth for the QuickDock menu
# icons. This generates the per-platform data files from it:
#
#   windows/tray-app/Icons.g.cs                      (C# / GDI+)
#   macos/menu-bar-app/FalconPulsar/Icons.g.swift    (Swift / AppKit)
#
# Same contract as sync-version.sh: run it after editing the source, and CI
# runs `--check` so a forgotten regeneration can never reach main.
#
# The generated files carry only DATA -- the path strings and their draw
# modes. The renderers that consume them are hand-written and live beside
# them, because a generator that emits drawing code would have to be right
# about two graphics APIs at once; a generator that emits a string table has
# to be right about nothing.
#
#   ./scripts/sync-icons.sh            regenerate
#   ./scripts/sync-icons.sh --check    exit 1 if either file has drifted
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEF="$ROOT/shared/icons/icons.def"
CS_OUT="$ROOT/windows/tray-app/Icons.g.cs"
SWIFT_OUT="$ROOT/macos/menu-bar-app/FalconPulsar/Icons.g.swift"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

[ -r "$DEF" ] || { echo "error: cannot read $DEF" >&2; exit 1; }

# -- Validate before generating -----------------------------------------------
#
# A malformed line would otherwise become a malformed literal in two languages
# and surface as a compile error with no hint of where it came from. Both
# renderers accept ONLY absolute M/L/C/Z, so reject anything else here where
# the message can name the line.
awk -F'|' '
    /^[[:space:]]*(#|$)/ { next }
    NF != 3 { printf "icons.def:%d: expected name|mode|path\n", NR; bad=1; next }
    {
        name = $1; mode = $2; path = $3
        gsub(/^[ \t]+|[ \t]+$/, "", name)
        gsub(/^[ \t]+|[ \t]+$/, "", mode)
        gsub(/^[ \t]+|[ \t]+$/, "", path)
        if (name !~ /^[a-z][a-z0-9-]*$/) {
            printf "icons.def:%d: bad icon name %s\n", NR, name; bad=1
        }
        if (mode != "F" && mode != "K" && mode !~ /^S[0-9]+(\.[0-9]+)?$/) {
            printf "icons.def:%d: bad mode %s (want F, K or S<width>)\n", NR, mode; bad=1
        }
        # Every token must be a command letter or a number.
        n = split(path, tok, /[ ,]+/)
        for (i = 1; i <= n; i++) {
            t = tok[i]
            if (t == "") continue
            if (t ~ /^[MLCZ]$/) continue
            if (t ~ /^-?[0-9]+(\.[0-9]+)?$/) continue
            printf "icons.def:%d: bad token %s (only absolute M L C Z and numbers)\n", NR, t
            bad=1
        }
        if (path !~ /^M /) {
            printf "icons.def:%d: path must start with M\n", NR; bad=1
        }
    }
    END { exit bad ? 1 : 0 }
' "$DEF" || { echo "error: icons.def is invalid (see above)" >&2; exit 1; }

# -- Emit ---------------------------------------------------------------------

banner_cs() {
    cat <<'EOF'
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 FalconPulsar Contributors
//
// <auto-generated>
//   GENERATED FROM shared/icons/icons.def BY scripts/sync-icons.sh
//   DO NOT EDIT. Edit icons.def and re-run the script; CI runs
//   `scripts/sync-icons.sh --check` and fails if this file has drifted.
//
//   Data only. The renderer is IconRenderer.cs, hand-written beside this.
// </auto-generated>

namespace FalconPulsar.Tray
{
    internal static class Icons
    {
        // name -> ordered subpaths, each (mode, path data).
        //   F     fill          K  fill in the knockout (background) colour
        //   S<w>  stroke width <w> in 24-grid units
        internal static readonly System.Collections.Generic.Dictionary<string, (string Mode, string Data)[]> All =
            new System.Collections.Generic.Dictionary<string, (string Mode, string Data)[]>
        {
EOF
}

banner_swift() {
    cat <<'EOF'
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 FalconPulsar Contributors
//
// GENERATED FROM shared/icons/icons.def BY scripts/sync-icons.sh
// DO NOT EDIT. Edit icons.def and re-run the script; CI runs
// `scripts/sync-icons.sh --check` and fails if this file has drifted.
//
// Data only. The renderer is IconRenderer.swift, hand-written beside this.

import Foundation

enum Icons {
    /// One subpath: how to paint it, and the path itself.
    ///   F     fill          K  fill in the knockout (background) colour
    ///   S<w>  stroke width <w> in 24-grid units
    struct SubPath {
        let mode: String
        let data: String
    }

    static let all: [String: [SubPath]] = [
EOF
}

emit_cs() {
    banner_cs
    awk -F'|' '
        /^[[:space:]]*(#|$)/ { next }
        {
            name = $1; mode = $2; path = $3
            gsub(/^[ \t]+|[ \t]+$/, "", name)
            gsub(/^[ \t]+|[ \t]+$/, "", mode)
            gsub(/^[ \t]+|[ \t]+$/, "", path)
            if (!(name in seen)) { order[++n] = name; seen[name] = "" }
            entries[name] = entries[name] sprintf("                (\"%s\", \"%s\"),\n", mode, path)
        }
        END {
            for (i = 1; i <= n; i++) {
                nm = order[i]
                printf "            [\"%s\"] = new (string, string)[]\n            {\n", nm
                printf "%s", entries[nm]
                printf "            },\n"
            }
        }
    ' "$DEF"
    cat <<'EOF'
        };
    }
}
EOF
}

emit_swift() {
    banner_swift
    awk -F'|' '
        /^[[:space:]]*(#|$)/ { next }
        {
            name = $1; mode = $2; path = $3
            gsub(/^[ \t]+|[ \t]+$/, "", name)
            gsub(/^[ \t]+|[ \t]+$/, "", mode)
            gsub(/^[ \t]+|[ \t]+$/, "", path)
            if (!(name in seen)) { order[++n] = name; seen[name] = "" }
            entries[name] = entries[name] sprintf("            SubPath(mode: \"%s\", data: \"%s\"),\n", mode, path)
        }
        END {
            for (i = 1; i <= n; i++) {
                nm = order[i]
                printf "        \"%s\": [\n", nm
                printf "%s", entries[nm]
                printf "        ],\n"
            }
        }
    ' "$DEF"
    cat <<'EOF'
    ]
}
EOF
}

if [ "$CHECK" = "1" ]; then
    rc=0
    for pair in "$CS_OUT:emit_cs" "$SWIFT_OUT:emit_swift"; do
        out="${pair%%:*}"; fn="${pair##*:}"
        if [ ! -f "$out" ]; then
            echo "drift: $out does not exist" >&2; rc=1; continue
        fi
        if ! diff -q <("$fn") "$out" >/dev/null 2>&1; then
            echo "drift: $out does not match shared/icons/icons.def" >&2
            diff <("$fn") "$out" | head -20 >&2 || true
            rc=1
        fi
    done
    if [ "$rc" = "0" ]; then
        echo "Both icon files match shared/icons/icons.def ($(grep -cv '^[[:space:]]*\(#\|$\)' "$DEF") subpaths)."
    fi
    exit $rc
fi

emit_cs    > "$CS_OUT"
emit_swift > "$SWIFT_OUT"
echo "Wrote:"
echo "  $CS_OUT"
echo "  $SWIFT_OUT"
